name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  PHP-Composer:

    runs-on: ubuntu-latest
    


    steps:
    - uses: actions/checkout@v3
    
    - name: check composer version
      run: composer -v
    
    - name: Install PHP and Composer
      run: |
        sudo apt-get update
        sudo apt-get install -y php-cli php-zip unzip
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    
    
    - name: check composer version
      run: composer -v
      
    - name: list files
      run: ls -la
      
    - name: execute php composer
      run: composer install
