name: PHP-CI

on:
  push:
    branches: [main] # Trigger the workflow on main branch push
  pull_request:
    branches: [main] # Trigger the workflow on main branch pull requests
  workflow_dispatch:
    inputs:
      php-version: 
        type: string
        description: PHP Version required by php composer
        required: true
        default: 8.1

      composer-version: 
        type: string
        description: Composer Version required
        required: true
        default: 2.5.4

jobs:
  PHP-Composer:
    runs-on: self-hosted
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PHP 8.1 if not installed
      run: |
        if php -v | grep -q "PHP 8.1"; then
          echo "PHP 8.1 is installed"
          echo "skipping PHP install"
        else
          echo "PHP 8.1 is not installed"
          echo "Installing PHP 8.1"
          sudo apt-get update
          sudo apt-get install -y php-cli php-zip unzip
        fi

    - name: Install PHP Composer if not installed
      run: |
        if composer -v | grep -q "Composer (version 2.5.4)"; then
          echo "Composer 2.5.4 is installed"
          echo "skipping Composer install"
        else
          echo "Composer 2.5.4 is not installed"
          echo "Installing Composer 2.5.4"
          #curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          sudo apt install composer -y
        fi

    - name: Run composer
      run: |
        composer install
        
    - name: List Dir
      run: ls -la


  Unit-Test:
    needs: PHP-Composer
    runs-on: self-hosted
    steps:
    - name: List Dir
      run: ls -la
      
    - name: Run PHP Unit Test
      run: vendor/bin/phpunit
